# import os
# # from telegram.ext import ContextTypes
# from typing import TypeVar
# # from telegram import Update
# # from telegram.ext.filters import Text, Regex
# # from utils.language import multilanguage
#
# CTX = TypeVar("CTX", bound=ContextTypes.DEFAULT_TYPE)
# UPD = TypeVar("UPD", bound=Update)
#
# PASSWORD = os.getenv("PASSWORD")
# PAGINATION_PAGE = os.getenv("PAGINATION_PAGE")
#
# EXCLUDE = ~(
#     Regex(r"^\/start\s*(\w+)?$")
#     | Text(multilanguage.get_all("buttons.back", "main_menu.feedback"))
# )
#
#
# MONTHS_UZBEK = {
#     1: "Yanvar",
#     2: "Fevral",
#     3: "Mart",
#     4: "Aprel",
#     5: "May",
#     6: "Iyun",
#     7: "Iyul",
#     8: "Avgust",
#     9: "Sentabr",
#     10: "Oktabr",
#     11: "Noyabr",
#     12: "Dekabr",
# }
#
#
# REGISTER_NAME = "REGISTER_NAME"
# REGISTER_NUMBER = "REGISTER_NUMBER"
#
# MAIN_MENU = "MAIN_MENU"
#
# NEUTRAL_MENU = "NEUTRAL_MENU"
#
# REGISTER_TARIFF = "REGISTER_TARIFF"
#
#
# REGISTER_PAYMENT_CARD = "REGISTER_PAYMENT_CARD"
# REGISTER_PAYMENT_EXPIRY = "REGISTER_PAYMENT_EXPIRY"
#
#
# MEETINGS = "MEETINGS"
#
# REGISTER_PAYMENT_OTP = "REGISTER_PAYMENT_OTP"
#
# REGISTER_PAYMENT_RETRY = "REGISTER_PAYMENT_RETRY"
#
#
# SETTINGS = "SETTINGS"
# SETTINGS_CARDS = "SETTINGS_CARDS"
#
#
# MEETINGS_CREATE_NAME = "MEETINGS_CREATE_NAME"
# MEETINGS_CREATE_NUMBER = "MEETINGS_CREATE_NUMBER"
# MEETINGS_CREATE_TIME = "MEETINGS_CREATE_TIME"
#
#
# MEETING_LIST = "MEETING_LIST"
#
# MEETING_ACTIONS = "MEETING_ACTIONS"
#
#
# MEETING_NEW_TIME = "MEETING_NEW_TIME"
# # MEETING_MOVE_DATE_OR_TIME = "MEETING_MOVE_DATE_OR_TIME"
# # MEETING_MOVE_TIME = "MEETING_MOVE_TIME"
#
#
# MEETING_NEW_DURATION = "MEETING_NEW_DURATION"
#
# MEETING_NEW_DESCRIPTION = "MEETING_NEW_DESCRIPTION"
#
# DOCUMENTS = "MEETING_DOCUMENTS"
#
# DOCUMENTS_CREATE_NAME = "MEETING_DOCUMENTS_CREATE_NAME"
# DOCUMENTS_CREATE_FILE = "MEETING_DOCUMENTS_CREATE_FILE"
#
# FINANCE = "FINANCE"
#
# FINANCE_INCOME_REASON = "FINANCE_INCOME_REASON"
# FINANCE_INCOME_AMOUNT = "FINANCE_INCOME_AMOUNT"
#
#
# FINANCE_EXPENSE_REASON = "FINANCE_EXPENSE_REASON"
# FINANCE_EXPENSE_AMOUNT = "FINANCE_EXPENSE_AMOUNT"
#
#
# SETTINGS_CARDS_CONNECT_CARD = "SETTINGS_CARDS_CONNECT_CARD"
# SETTINGS_CARDS_CONNECT_EXPIRY = "SETTINGS_CARDS_CONNECT_EXPIRY"
#
#
# SETTINGS_CARDS_CONNECT_OTP = "SETTINGS_CARDS_CONNECT_OTP"
#
#
# CHATGPT = "CHATGPT"
#
# GPT_MEET_NUMBER_CHANGE = "GPT_MEET_NUMBER_CHANGE"
#
# MEETING_ACTIONS_CANCEL = "MEETING_ACTIONS_CANCEL"